### ISSUE TITLE
Bug: UX: Checkmarks for Upload

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/3D-DFG-Viewer#12]
* [x] @thedworak Bug 1: In case of unsupported format error message with green check mark and green color (better: exclamation mark and red).
* [x] @thedworak Bug 2: If the upload is successful, the checkmarks are not displayed correctly

**Comment by ClemensBeck** [comment]
Daniel need more feedback about the steps while uploading (Bug 2), Clemens will ask Samuel for it

**Comment by SamuelGlowka** [comment]
![fbx-archive_cpdp-rose-window_6a](https://user-images.githubusercontent.com/111511033/185404436-a4c6b38c-260c-4d1b-9727-6ebfd316837e.png)
I believe it is this screenshot from June the bug is referring to. I tested a series of differently structured archives and this one consisted of two folders "source" and "textures" just as I downloaded the model from sketchfab.

The archive: [Uploading fbx-archive_cpdp-rose-window_6.zip…]()

I uploaded it again to: [https://3d-repository.hs-mainz.de/wisski/navigate/552/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128](https://3d-repository.hs-mainz.de/wisski/navigate/552/view?wisski_bundle=bd3d7baa74856d141bcff7b4193fa128)

Here the response: 
![Screenshot (128)](https://user-images.githubusercontent.com/111511033/185406466-4c5ac3d5-7be5-4604-9977-4c30a234f871.png)
![Screenshot (129)](https://user-images.githubusercontent.com/111511033/185406487-345953be-2cd8-4232-86a7-1c267eb3add8.png)

**Comment by thedworak** [comment]
Added some conditions, I don't see field that can appear without content anymore.
